spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    open-in-view: false
    show-sql: true
  #      format_sql: true
  #      use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    p6spy: info
    org:
      #      hibernate.SQL: debug
      springframework.security: info